name: hardened-node-publish

on: 
  push:
    paths:
    - '.github/actions/**'
    - '.github/workflows/hardened-node-*.yml'
    - 'hardened-node/**'

env:
  IMAGE_NAME: hardened-node  
  IMAGE_PATH: ghcr.io/${{ github.repository }}/hardened-node
  DOCKER_CONTENT_TRUST: 1
  BASE_IMAGE: photon:latest

jobs:
  publish-hardened-dockerfile:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          path: container-images

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Container Registry
        run: docker login ghcr.io --username ${{ github.repository_owner }} --password ${{ secrets.GHCR_TOKEN }}

      - name: Get Node version number
        env:
          DOCKER_CONTENT_TRUST: 0
        id: GetNodeVersion
        run: |
          version=$(docker run --rm ${{ env.BASE_IMAGE }} node --version | tr -d ' ')
          echo "node_version=node-$version" >> $GITHUB_ENV
          echo "node_version=node-$version" >> $GITHUB_OUTPUT
          echo "node_version_run=node-$version.${{ github.run_number }}" >> $GITHUB_ENV
          echo "node_version_run=node-$version.${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Build and Push image
        uses: docker/build-push-action@v5
        with:
          context: ./container-images
          file: ./container-images/${{ env.IMAGE_NAME }}/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_PATH }}:latest
            ${{ env.IMAGE_PATH }}:${{ env.node_version }}
            ${{ env.IMAGE_PATH }}:${{ env.node_version_run }}
