name: hardened-photon-test

on: 
  push:
    paths:
    - '.github/actions/**'
    - '.github/workflows/hardened-photon-*.yml'
    - 'hardened-photon/**'
  pull_request:
    paths:
      - 'github/workflows/hardened-photon-*.yml'
      - 'hardened-photon/**'
  schedule:
    - cron:  0 0 * * 0

env:
  IMAGE_NAME: hardened-photon
  IMAGE_PATH: ${{vars.REGISTRY}}/${{github.repository}}/hardened-photon
  DOCKER_CONTENT_TRUST: 1
  BASE_IMAGE: photon:latest

jobs:
  test-hardened-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: container-images

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and export to DOCKER
        uses: docker/build-push-action@v5
        with: 
          context: ./container-images
          file: ./container-images/${{env.IMAGE_NAME}}/Dockerfile
          load: true
          tags: ${{env.IMAGE_PATH}}:test

      - uses: ruslanbahna/reusable-actions/container-image-size@v0.0.4
        env: 
          DOCKER_CONTENT_TRUST: 0
        with:
          built-image: ${{ env.IMAGE_PATH}}:test
          base-image: ${{ env.BASE_IMAGE }}

      - uses: ruslanbahna/reusable-actions/docker-bench-security@v0.0.8
        with:
          image-name: ${{ env.IMAGE_PATH}}:test

      - name: Run Trivy Vulnerability scanner test
        uses: aquasecurity/trivy-action@master
        env: 
          DOCKER_CONTENT_TRUST: 0
        with:
          image-ref: ${{env.IMAGE_PATH}}:test
          exit-code: 1
          severity: HIGH,CRITICAL