name: hardened-node-publish

on: 
  push:
    paths:
    - '.github/actions/**'
    - '.github/workflows/hardened-node-*.yml'
    - 'hardened-node/**'

env:
  IMAGE_NAME: hardened-node  
  IMAGE_PATH: ghcr.io/${{ github.repository }}/hardened-node
  DOCKER_CONTENT_TRUST: 1
  BASE_IMAGE: photon:latest

jobs:
  publish-hardened-dockerfile:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          path: container-images

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Container Registry
        run: docker login ghcr.io --username ${{ github.repository_owner }} --password ${{ secrets.GHCR_TOKEN }}

      - name: Get OS version
        env:
          DOCKER_CONTENT_TRUST: 0
        id: GetVersion
        run: |
          major_minor=$(docker run --rm ${{ env.BASE_IMAGE }} lsb_release --short --release)
          echo "major_minor=photon-$major_minor" >> $GITHUB_ENV
          echo "major_minor=photon-$major_minor" >> $GITHUB_OUTPUT  # Fix output setting

      - name: Build and export to DOCKER
        uses: docker/build-push-action@v5
        with: 
          context: ./container-images
          file: ./container-images/${{ env.IMAGE_NAME }}/Dockerfile
          load: true
          tags: |
            ${{ env.IMAGE_PATH }}:${{ env.major_minor }}.${{ github.run_number }}
            ${{ env.IMAGE_PATH }}:${{ env.major_minor }}
            ${{ env.IMAGE_PATH }}:latest

      - name: Get Node version
        env:
          DOCKER_CONTENT_TRUST: 0
        id: GetNodeVersion
        run: |
          version=$(docker run --rm ${{ env.IMAGE_PATH }}:${{ env.major_minor }}.${{ github.run_number }} node --version | tr -d ' ')
          echo "version=node-$version" >> $GITHUB_ENV
          major_minor=${version%.*}
          echo "major_minor=node-$major_minor" >> $GITHUB_ENV
          echo "version=node-$version" >> $GITHUB_OUTPUT  # Fix output setting
          echo "major_minor=node-$major_minor" >> $GITHUB_OUTPUT  # Fix output setting

      - name: Build and Push image
        uses: docker/build-push-action@v5
        with:
          context: ./container-images
          file: ./container-images/${{ env.IMAGE_NAME }}/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_PATH }}:${{ env.major_minor }}.${{ github.run_number }}
            ${{ env.IMAGE_PATH }}:${{ env.major_minor }}
            ${{ env.IMAGE_PATH }}:latest
            ${{ env.IMAGE_PATH }}:${{ env.version }}
            ${{ env.IMAGE_PATH }}:${{ env.major_minor }}
